#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2> /dev/null | grep -oE "[A-Z0-9]+")
COMMIT=$(cat $1)

if ! [[ $COMMIT =~ [A-Z]+[A-Z]+" " ]] && [ -n "$BRANCH_NAME" ]; then
    echo "$BRANCH_NAME $COMMIT" > $1
fi
